-- AlterTable
ALTER TABLE "Team" ADD COLUMN     "goalsDifference" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "played" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "position" INTEGER NOT NULL DEFAULT 0;
